homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 63.43049
  longitude: 10.39506
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 40
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  #customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# recorder: 
#   exclude:
#     enteties:
#       - sensor.date
#       - sensor.date_time
#       - sensor.time
#       - sensor.time_date
#       - sensor.time_utc

recorder:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - binary_sensor
      - light

# Enables support for tracking state changes over time
history:
  use_include_order: true
  include:
    entities:
      - light.soverom_lys
      - light.ac_1
      - light.ac_2
      - light.ac_3
      - light.ac_4
      - switch.ac_5
      - switch.ac_6
      - switch.ac_7
      - switch.ac_8
      - sensor.0x00158d00025d859a_temperature
      - sensor.0x00158d00025ee67a_temperature
      - sensor.kjeller_temperature
      - sensor.soverom_temperature
      - sensor.soverom_aqara_sensor_temperature
      - sensor.stue_temperature
      - sensor.living_room_temperature
      - sensor.loft_temperature
      - sensor.0x00158d00025d859a_humidity
      - sensor.0x00158d00025ee67a_humidity
      - sensor.kjeller_humidity
      - sensor.soverom_humidity
      - sensor.soverom_aqara_sensor_humidity
      - sensor.stue_humidity
      - sensor.loft_humidity
      - sensor.living_room_light_level
      - light.living_room
    # domain: 
    #   - binary_sensor
    #   - media_player

# View all events in a logbook
# logbook:
#   include:
#     domains:
#       - sensor
#       - binary_sensor
#       - switch
#       - light
#       - media_player
#   exclude:
#     entities:
#       - sensor.date
#       - sensor.date_time
#       - sensor.time
#       - sensor.time_date
#       - sensor.time_utc

# Enables a map showing the location of tracked devices
#map:

# Track the sun
#sun:


# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

# System health
system_health:


#group: !include groups.yaml
automation: !include automations.yaml

### Automation ###
#automation: !include_dir_merge_list automation


###  Sensors  ###
#  Sensors are anything (hardware or software) that has a state.
sensor: !include_dir_merge_list sensors

### Input Boolean ###
# The input_boolean component allows the user to define boolean values
# that can be controlled via the frontend and can be used within conditions of automation.
input_boolean: !include custom_components/input_boolean.yaml

### Input Number ###
input_number: !include custom_components/input_number.yaml

http:
    #api_password: !secret http_password
    ssl_certificate: /etc/letsencrypt/live/prestegaard.duckdns.org/fullchain.pem
    ssl_key: /etc/letsencrypt/live/prestegaard.duckdns.org/privkey.pem
    base_url: prestegaard.duckdns.org:8123     
    ip_ban_enabled: True
    login_attempts_threshold : 3


#api:

mqtt:
    broker: 127.0.0.1 
    port: 1883
    client_id: home-assistant-1
    keepalive: 60
    username: haagon
    password: !secret mqtt_password
    protocol: 3.1 
    discovery: true
    birth_message: 
      topic: 'hass/status'
      payload: 'online'
    will_message: 
      topic: 'hass/status'
      payload: 'offline'


light:
######################################## MQTT AC LIGHTS ###########################################
  - platform: mqtt
    name: "AC 1"
    state_topic: "/AC/outletConfirm1/"
    command_topic: "/AC/outlet1/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    
  
  - platform: mqtt
    name: "AC 2"
    state_topic: "/AC/outletConfirm2/"
    command_topic: "/AC/outlet2/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    

  - platform: mqtt
    name: "AC 3"
    state_topic: "/AC/outletConfirm3/"
    command_topic: "/AC/outlet3/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    
  
  - platform: mqtt
    name: "AC 4"
    state_topic: "/AC/outletConfirm4/"
    command_topic: "/AC/outlet4/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true

  - platform: group
    name: Soverom Lys
    entities:
      #- light.ac_1
      - light.ac_2
      - light.ac_3
      - light.ac_4
      - light.hue_bedroom_low
      - light.hue_bedroom_high

switch:
######################################## MQTT AC OUTLETS ###########################################
  - platform: mqtt
    name: "AC 5"
    state_topic: "/AC/outletConfirm5/"
    command_topic: "/AC/outlet5/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    

  - platform: mqtt
    name: "AC 6"
    state_topic: "/AC/outletConfirm6/"
    command_topic: "/AC/outlet6/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    

  - platform: mqtt
    name: "AC 7"
    state_topic: "/AC/outletConfirm7/"
    command_topic: "/AC/outlet7/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true   

  - platform: mqtt
    name: "AC 8"
    state_topic: "/AC/outletConfirm8/"
    command_topic: "/AC/outlet8/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    

######################################## MQTT NAD REMOTE ###########################################
  - platform: mqtt
    name: "NAD POWER"    
    command_topic: "/NAD/"
    payload_on: "POWER_ON"
    payload_off: "POWER_OFF"
    optimistic: false
    retain: false
    value_template: '{{ value }}'

  - platform: mqtt
    name: "NAD VOLUME"
    command_topic: "/NAD/"
    payload_on: "VOLUME+"
    payload_off: "VOLUME-" 

  - platform: mqtt
    name: "NAD CHROMECAST"
    command_topic: "/NAD/"
    payload_on: "INPUT_CHROMECAST"
 
  - platform: mqtt
    name: "NAD SOFA"
    command_topic: "/NAD/"
    payload_on: "INPUT_SOFA"

binary_sensor:
  - platform: huesensor
  

#device_tracker:
#  - platform: huesensor

group:
  default_view:
    name: Overview
    view: yes
    entities:
      - group.alarmclock
      - group.switch
      - group.automation_view
  alarmclock:
    name: Wake Me Up
    entities: 
      - automation.wake_me_up
      - sensor.alarm_time
      - input_number.alarmhour
      - input_number.alarmminutes
      - input_boolean.alarmweekday
  switch:
    name: Outlets Bedroom
    view: true
    entities:
      - switch.ac_5
      - switch.ac_6
      - switch.ac_7
      - switch.ac_8
  
  soverom_klima:
    name: thingy52_soverom
    entities:
      - sensor.soverom_temperature
      - sensor.soverom_humidity
      - sensor.soverom_co2
      - sensor.soverom_tvoc
      - sensor.soverom_pressure
      - sensor.soverom_battery
  hue:
    entities:
      - binary_sensor.living_room_motion_sensor
      - sensor.living_room_temperature
      - sensor.living_room_light_level
      
  automation_view:
    name: Automation
    view: true
    entities:
      - group.all_automations
      - group.all_scripts
