 # First thingy
- platform: thingy52
 # Add your custom name here
  friendly_name: Soverom
  scan_interval: 60
 # 1 = 1 s interval
 # 2 = 10 s interval
 # 3 = 60 s interval
  gas_interval: 3
  mac: "DA:96:FB:EC:11:11"
  sensors:
    - 'temperature'
    - 'humidity'
    - 'co2'
    - 'tvoc'
    - 'pressure'
    - 'battery'

- platform: thingy52
 # Add your custom name here
  friendly_name: Loft
  scan_interval: 60
 # 1 = 1 s interval
 # 2 = 10 s interval
 # 3 = 60 s interval
  gas_interval: 3
  mac: "F9:89:C0:EC:3A:4A"
  sensors:
    - 'temperature'
    - 'humidity'
    - 'co2'
    - 'tvoc'
    - 'pressure'
    - 'battery'

- platform: thingy52
 # Add your custom name here
  friendly_name: Stue
  scan_interval: 60
 # 1 = 1 s interval
 # 2 = 10 s interval
 # 3 = 60 s interval
  gas_interval: 3
  mac: "E1:BA:5D:3B:AF:EA"
  sensors:
    - 'temperature'
    - 'humidity'
    - 'co2'
    - 'tvoc'
    - 'pressure'
    - 'battery'


- platform: thingy52
 # Add your custom name here
  friendly_name: Kjeller
  scan_interval: 60
 # 1 = 1 s interval
 # 2 = 10 s interval
 # 3 = 60 s interval
  gas_interval: 3
  mac: "F2:A0:A2:DB:69:7B"
  sensors:
    - 'temperature'
    - 'humidity'
    - 'co2'
    - 'tvoc'
    - 'pressure'
    - 'battery'


